@startuml

    package de.gematik.ti.cardreader.provider.nfc.control {
      class NfcCardReaderController {
                {static} - LOG : Logger
                {static} - instance : NfcCardReaderController
                - cardReaders : ArrayList<ICardReader>
                - nfcManager : NfcManager
                - nfcAdapter : NfcAdapter
                - initialized : boolean
                - context : Context
                - activity : Activity
                - NfcCardReaderController()
                {static} + getInstance()
                + getCardReaders()
                - init()
                {static} - getActivity()
            }
    }


  NfcCardReaderController -up-|> AbstractAndroidCardReaderController

@enduml
