@startuml

package de.gematik.ti.cardreader.provider.nfc.control {

        class NfcReceiver {
                {static} - LOG : Logger
                + onReceive()
        }
      }

NfcReceiver -up-|> BroadcastReceiver

@enduml
